name: Geometry Library CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      SOLUTION_NAME: GeometryLibrary.sln
      TEST_PROJECT_PATH: GeometryLibrary.Tests/GeometryLibrary.Tests.csproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.nuget/packages
          **/bin
          **/obj
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}
      
    - name: Run unit tests
      run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration Debug --no-build 
